services:
  backend:
    build:
      context: ./backend
    ports:
      - "5267:5267"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CocktailDB;User Id=sa;Password=YourStrong@Password;TrustServerCertificate=True;
    depends_on:
      - db
    volumes:
      - ./UploadedImages:/app/UploadedImages

  frontend:
    build:
      context: ./frontendTerranova
    ports:
      - "4200:4200"
    environment:
      - BACKEND_URL=http://backend:5267
    depends_on:
      - backend
      - translator

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    user: "0"

  translator:
    build:
      context: ./LibreTranslate
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,es,fr,it,de,ja,zh
      - LT_UPDATE_MODELS=true
    volumes:
      - libretranslate_models:/home/libretranslate/.local:rw

volumes:
  db_data:
  libretranslate_models: