// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CocktailDebacle.API.Migrations
{
    [DbContext(typeof(CocktailDbContext))]
    partial class CocktailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByUser");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cocktails");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppPermissions")
                        .HasColumnType("bit");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanDrinkAlcohol")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .HasMaxLength(58)
                        .HasColumnType("nvarchar(58)");

                    b.Property<string>("Country")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.PrimitiveCollection<string>("CreatedCocktails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteCocktails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cocktail", b =>
                {
                    b.OwnsOne("CocktailApiDrink", "Drink", b1 =>
                        {
                            b1.Property<int>("CocktailId")
                                .HasColumnType("int");

                            b1.Property<string>("DateModified")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_DateModified")
                                .HasAnnotation("Relational:JsonPropertyName", "dateModified");

                            b1.Property<string>("IdDrink")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_IdDrink")
                                .HasAnnotation("Relational:JsonPropertyName", "idDrink");

                            b1.Property<string>("StrAlcoholic")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrAlcoholic")
                                .HasAnnotation("Relational:JsonPropertyName", "strAlcoholic");

                            b1.Property<string>("StrCategory")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrCategory")
                                .HasAnnotation("Relational:JsonPropertyName", "strCategory");

                            b1.Property<string>("StrCreativeCommonsConfirmed")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrCreativeCommonsConfirmed")
                                .HasAnnotation("Relational:JsonPropertyName", "strCreativeCommonsConfirmed");

                            b1.Property<string>("StrDrink")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrDrink")
                                .HasAnnotation("Relational:JsonPropertyName", "strDrink");

                            b1.Property<string>("StrDrinkAlternate")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrDrinkAlternate")
                                .HasAnnotation("Relational:JsonPropertyName", "strDrinkAlternate");

                            b1.Property<string>("StrDrinkThumb")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrDrinkThumb")
                                .HasAnnotation("Relational:JsonPropertyName", "strDrinkThumb");

                            b1.Property<string>("StrGlass")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrGlass")
                                .HasAnnotation("Relational:JsonPropertyName", "strGlass");

                            b1.Property<string>("StrIBA")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIBA")
                                .HasAnnotation("Relational:JsonPropertyName", "strIBA");

                            b1.Property<string>("StrImageAttribution")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrImageAttribution")
                                .HasAnnotation("Relational:JsonPropertyName", "strImageAttribution");

                            b1.Property<string>("StrImageSource")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrImageSource")
                                .HasAnnotation("Relational:JsonPropertyName", "strImageSource");

                            b1.Property<string>("StrIngredient1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient1")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient1");

                            b1.Property<string>("StrIngredient10")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient10")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient10");

                            b1.Property<string>("StrIngredient11")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient11")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient11");

                            b1.Property<string>("StrIngredient12")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient12")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient12");

                            b1.Property<string>("StrIngredient13")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient13")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient13");

                            b1.Property<string>("StrIngredient14")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient14")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient14");

                            b1.Property<string>("StrIngredient15")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient15")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient15");

                            b1.Property<string>("StrIngredient2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient2")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient2");

                            b1.Property<string>("StrIngredient3")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient3")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient3");

                            b1.Property<string>("StrIngredient4")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient4")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient4");

                            b1.Property<string>("StrIngredient5")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient5")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient5");

                            b1.Property<string>("StrIngredient6")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient6")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient6");

                            b1.Property<string>("StrIngredient7")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient7")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient7");

                            b1.Property<string>("StrIngredient8")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient8")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient8");

                            b1.Property<string>("StrIngredient9")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrIngredient9")
                                .HasAnnotation("Relational:JsonPropertyName", "strIngredient9");

                            b1.Property<string>("StrInstructions")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrInstructions")
                                .HasAnnotation("Relational:JsonPropertyName", "strInstructions");

                            b1.Property<string>("StrInstructionsDE")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrInstructionsDE")
                                .HasAnnotation("Relational:JsonPropertyName", "strInstructionsDE");

                            b1.Property<string>("StrInstructionsES")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrInstructionsES")
                                .HasAnnotation("Relational:JsonPropertyName", "strInstructionsES");

                            b1.Property<string>("StrInstructionsFR")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrInstructionsFR")
                                .HasAnnotation("Relational:JsonPropertyName", "strInstructionsFR");

                            b1.Property<string>("StrInstructionsIT")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrInstructionsIT")
                                .HasAnnotation("Relational:JsonPropertyName", "strInstructionsIT");

                            b1.Property<string>("StrInstructionsZH_HANS")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrInstructionsZH_HANS")
                                .HasAnnotation("Relational:JsonPropertyName", "strInstructionsZH-HANS");

                            b1.Property<string>("StrInstructionsZH_HANT")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrInstructionsZH_HANT")
                                .HasAnnotation("Relational:JsonPropertyName", "strInstructionsZH-HANT");

                            b1.Property<string>("StrMeasure1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure1")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure1");

                            b1.Property<string>("StrMeasure10")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure10")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure10");

                            b1.Property<string>("StrMeasure11")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure11")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure11");

                            b1.Property<string>("StrMeasure12")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure12")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure12");

                            b1.Property<string>("StrMeasure13")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure13")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure13");

                            b1.Property<string>("StrMeasure14")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure14")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure14");

                            b1.Property<string>("StrMeasure15")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure15")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure15");

                            b1.Property<string>("StrMeasure2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure2")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure2");

                            b1.Property<string>("StrMeasure3")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure3")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure3");

                            b1.Property<string>("StrMeasure4")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure4")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure4");

                            b1.Property<string>("StrMeasure5")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure5")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure5");

                            b1.Property<string>("StrMeasure6")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure6")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure6");

                            b1.Property<string>("StrMeasure7")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure7")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure7");

                            b1.Property<string>("StrMeasure8")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure8")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure8");

                            b1.Property<string>("StrMeasure9")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrMeasure9")
                                .HasAnnotation("Relational:JsonPropertyName", "strMeasure9");

                            b1.Property<string>("StrTags")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrTags")
                                .HasAnnotation("Relational:JsonPropertyName", "strTags");

                            b1.Property<string>("StrVideo")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Drink_StrVideo")
                                .HasAnnotation("Relational:JsonPropertyName", "strVideo");

                            b1.HasKey("CocktailId");

                            b1.ToTable("Cocktails");

                            b1.WithOwner()
                                .HasForeignKey("CocktailId");
                        });

                    b.Navigation("Drink")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
