import { Component, EventEmitter, Output  } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';

@Component({
  selector: 'app-country',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './country.component.html',
  styleUrl: './country.component.scss'
})
export class CountryComponent {
  @Output() countrySelected = new EventEmitter<string>();
  countries: string[] = [
    'Afghanistan',  
    'Albania',  
    'Algeria',  
    'Andorra',  
    'Angola',  
    'Antigua e Barbuda',  
    'Arabia Saudita',  
    'Argentina',  
    'Armenia',  
    'Australia',  
    'Austria',  
    'Azerbaigian',  
    'Bahamas',  
    'Bahrein',
    'Bangladesh',  
    'Barbados',  
    'Belgio',  
    'Belize',  
    'Benin',  
    'Bhutan',  
    'Bielorussia',  
    'Birmania',  
    'Bolivia',  
    'Bosnia ed Erzegovina',  
    'Botswana',  
    'Brasile',  
    'Brunei',  
    'Bulgaria',  
    'Burkina Faso',  
    'Burundi',  
    'Cambogia',  
    'Camerun',  
    'Canada',  
    'Capo Verde',  
    'Ciad',  
    'Cile',  
    'Cina',  
    'Cipro',  
    'Colombia',  
    'Comore',  
    'Corea del Nord',  
    'Corea del Sud',  
    'Costa d\'Avorio',  
    'Costa Rica',  
    'Croazia',  
    'Cuba',  
    'Danimarca',  
    'Dominica',  
    'Ecuador',  
    'Egitto',  
    'El Salvador',  
    'Emirati Arabi Uniti',  
    'Eritrea',  
    'Estonia',  
    'Eswatini',  
    'Etiopia',  
    'Figi',  
    'Filippine',  
    'Finlandia',  
    'Francia',  
    'Gabon',  
    'Gambia',  
    'Georgia',  
    'Germania',  
    'Ghana',  
    'Giamaica',  
    'Giappone',  
    'Gibuti',  
    'Giordania',  
    'Grecia',  
    'Grenada',  
    'Guatemala',  
    'Guinea',  
    'Guinea-Bissau',  
    'Guinea Equatoriale',  
    'Guyana',  
    'Haiti',  
    'Honduras',  
    'India',  
    'Indonesia',  
    'Iran',  
    'Iraq',  
    'Irlanda',  
    'Islanda',  
    'Israele',  
    'Italia',  
    'Kazakistan',  
    'Kenya',  
    'Kirghizistan',  
    'Kiribati',  
    'Kuwait',  
    'Laos',  
    'Lesotho',  
    'Lettonia',  
    'Libano',  
    'Liberia',  
    'Libia',  
    'Liechtenstein',  
    'Lituania',  
    'Lussemburgo',  
    'Macedonia del Nord',  
    'Madagascar',  
    'Malawi',  
    'Malesia',  
    'Maldive',  
    'Mali',  
    'Malta',  
    'Marocco',  
    'Marshall',  
    'Mauritania',  
    'Mauritius',  
    'Messico',  
    'Micronesia',  
    'Moldavia',  
    'Monaco',  
    'Mongolia',  
    'Montenegro',  
    'Mozambico',  
    'Namibia',  
    'Nauru',  
    'Nepal',  
    'Nicaragua',  
    'Niger',  
    'Nigeria',  
    'Norvegia',  
    'Nuova Zelanda',  
    'Oman',  
    'Paesi Bassi',  
    'Pakistan',  
    'Palau',  
    'Panama',  
    'Papua Nuova Guinea',  
    'Paraguay',  
    'Perù',  
    'Polonia',  
    'Portogallo',  
    'Qatar',  
    'Regno Unito',  
    'Repubblica Centrafricana',  
    'Repubblica Ceca',  
    'Repubblica Democratica del Congo',  
    'Repubblica Dominicana',  
    'Romania',  
    'Ruanda',  
    'Russia',  
    'Saint Kitts e Nevis',  
    'Saint Lucia',  
    'Saint Vincent e Grenadine',  
    'Samoa',  
    'San Marino',  
    'Santa Sede',  
    'São Tomé e Príncipe',  
    'Senegal',  
    'Serbia',  
    'Seychelles',  
    'Sierra Leone',  
    'Singapore',  
    'Siria',  
    'Slovacchia',  
    'Slovenia',  
    'Somalia',  
    'Spagna',  
    'Sri Lanka',  
    'Stati Uniti d\'America',  
    'Sudan',  
    'Sudan del Sud',  
    'Suriname',  
    'Svezia',  
    'Svizzera',  
    'Tailandia',  
    'Taiwan',  
    'Tanzania',  
    'Togo',  
    'Tonga',  
    'Trinidad e Tobago',  
    'Tunisia',  
    'Turchia',  
    'Turkmenistan',  
    'Tuvalu',  
    'Ucraina',  
    'Uganda',  
    'Ungheria',  
    'Uruguay',  
    'Uzbekistan',  
    'Vanuatu',  
    'Venezuela',  
    'Vietnam',  
    'Yemen',  
    'Zambia',  
    'Zimbabwe'
  ];
  selectedCountry: string = '';

  ngOnInit() {
    console.log('Lista delle nazioni:', this.countries);
  }

  onCountryChange() {
    this.countrySelected.emit(this.selectedCountry);
  }
}
